#!/bin/bash

echo "Starting provisioning"
tty -s && mesg n
set -e
echo "export PATH=\"/opt/ghc/bin:\$PATH\"" >> ~/.bashrc
cat ~/.bashrc
pwd

source ~/.bashrc
sudo apt-get -y update
sudo apt-get -y upgrade
sudo aptitude install -y libgmp3-dev zlib1g-dev libbz2-dev git vim nmap

wget https://www.haskell.org/ghc/dist/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
tar xvf ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
cd ghc-7.8.4
./configure --prefix=/opt/ghc
sudo make install
cd ~/

curl -O https://www.haskell.org/cabal/release/cabal-1.22.0.0/Cabal-1.22.0.0.tar.gz
tar xzvf Cabal-1.22.0.0.tar.gz
cd Cabal-1.22.0.0

ghc --make Setup.hs
./Setup configure --user
./Setup build
./Setup install
#sudo -E PATH=$PATH ./Setup install
cd ~/

# get distributive
curl -O https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-install-1.22.0.0.tar.gz

# extract archive
tar xzvf cabal-install-1.22.0.0.tar.gz
cd cabal-install-1.22.0.0

# install
#sudo -E PATH=$PATH ./bootstrap.sh
./bootstrap.sh
echo "export PATH=\"~/.cabal/bin/:\$PATH\"" >> ~/.bashrc
source ~/.bashrc
cd ~/

git clone https://github.com/valderman/haste-compiler
cd haste-compiler
cabal install
haste-boot --dev
cd ../

haste-inst install --flags="-integer-gmp" hashable-1.2.3.1
haste-inst install react-haskell-1.3.0.1

cd snaplet-haste
cabal install
cd ../

cd photogrammetry
cabal install
cd ../

